# Generated by Django 4.2.5 on 2024-04-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier_app', '0002_order_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('manager', 'manager'), ('employee', 'employee')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='bill',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
