# Generated by Django 4.2.5 on 2024-04-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier_app', '0003_order_status_alter_order_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('booked', 'booked'), ('in_process', 'in_process'), ('delivered', 'delivered')], max_length=50, null=True),
        ),
    ]
